In [25]:
import numpy as np #1.26.4버전으로 설치해야함
from scipy.special import softmax

print(np.__version__)

1.26.4


# STEP 1: 입력 표현하기

In [26]:
print("Step 1: Input : 3 inputs, d_model=4")

# 4차원의 3개 입력 선언
x = np.array([[1.0, 0.0, 1.0, 0.0], # Input1
             [0.0, 2.0, 0.0, 2.0], # Input2
             [1.0, 1.0, 1.0, 1.0]]) # Input3

print(x)

Step 1: Input : 3 inputs, d_model=4
[[1. 0. 1. 0.]
 [0. 2. 0. 2.]
 [1. 1. 1. 1.]]


# STEP 2: 가중치 행렬 초기화

In [27]:
print("Step 2: weights 3 dimentions x d_model=4")
print("w_query")
w_query = np.array([[1 , 0, 1],
                    [1, 0, 0],
                    [0, 0, 1],
                    [0, 1, 1]])
print(w_query)

Step 2: weights 3 dimentions x d_model=4
w_query
[[1 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 1]]


In [28]:
print("w_key")
w_key=np.array([[0, 0, 1],
                [1, 1, 0],
                [0, 1, 0],
                [1, 1, 0]])
print(w_key)

w_key
[[0 0 1]
 [1 1 0]
 [0 1 0]
 [1 1 0]]


In [29]:
print("w_value")
w_value = np.array([[0, 2, 0],
                    [0, 3, 0],
                    [1, 0, 3],
                    [1, 1, 0]])
print(w_value)

w_value
[[0 2 0]
 [0 3 0]
 [1 0 3]
 [1 1 0]]


# STEP3 : Q,K,V를 얻기 위한 행렬 곱셈

In [30]:
print("Step 3: Matrix multiplication to obtain Q,K,V")

print("Queries: x * w_query")
Q = np.matmul(x,w_query)
print(Q)

Step 3: Matrix multiplication to obtain Q,K,V
Queries: x * w_query
[[1. 0. 2.]
 [2. 2. 2.]
 [2. 1. 3.]]


In [31]:
print("Queries: x * w_key")
K = np.matmul(x,w_key)
print(K)

Queries: x * w_key
[[0. 1. 1.]
 [4. 4. 0.]
 [2. 3. 1.]]


In [32]:
print("Queries: x * w_value")
V = np.matmul(x, w_value)
print(V)

Queries: x * w_value
[[1. 2. 3.]
 [2. 8. 0.]
 [2. 6. 3.]]


# STEP4: 스케일링 된 어텐션 점수

In [33]:
print("Step 4: Scaled Attention Scores")
d_k = 1 # root(d_k=3은 1로 절삭)
attention_scores = (Q @ K.transpose())/d_k
print(attention_scores)

Step 4: Scaled Attention Scores
[[ 2.  4.  4.]
 [ 4. 16. 12.]
 [ 4. 12. 10.]]


# STEP5: 각 벡터에 대한 스케일링 된 softmax 어텐션 점수 

In [34]:
print("Step 5: Scaled softmax attention_scores for each vector")
attention_scores[0] = softmax(attention_scores[0])
attention_scores[1] = softmax(attention_scores[1])
attention_scores[2] = softmax(attention_scores[2])

print(attention_scores[0])
print(attention_scores[1])
print(attention_scores[2])

Step 5: Scaled softmax attention_scores for each vector
[0.06337894 0.46831053 0.46831053]
[6.03366485e-06 9.82007865e-01 1.79861014e-02]
[2.95387223e-04 8.80536902e-01 1.19167711e-01]


# STEP6 : 최종 어텐션 포함

In [35]:
print("Step6 : attention value obtained by score1/k*d * V")

print(V[0])
print(V[1])
print(V[2])

print("attention1")
# attention1=attention_scores[0].reshape(-1,1)
attention1=attention_scores[0][0]*V[0]
print(attention1)

print("attention2")
attention2=attention_scores[0][1]*V[1]
print(attention2)

print("attention3")
attention3=attention_scores[0][2]*V[2]
print(attention3)

Step6 : attention value obtained by score1/k*d * V
[1. 2. 3.]
[2. 8. 0.]
[2. 6. 3.]
attention1
[0.06337894 0.12675788 0.19013681]
attention2
[0.93662106 3.74648425 0.        ]
attention3
[0.93662106 2.80986319 1.40493159]


# STEP7 : 결과 합산

In [36]:
print("Step7: summed the results to create the first line of the output matrix")

attetnion_input1=attention1+attention2+attention3
print(attetnion_input1)

Step7: summed the results to create the first line of the output matrix
[1.93662106 6.68310531 1.59506841]


# STEP8: 나머지 입력들에 대해 단계 17 수행

In [38]:
print("Step8: Step 1 to 7 for input 1 to 3")
attention_head1 = np.random.random((3,64))
print(attention_head1)

Step8: Step 1 to 7 for input 1 to 3
[[0.68399414 0.78869461 0.54921383 0.17599309 0.66926646 0.66947449
  0.81900417 0.57156699 0.22317853 0.58679393 0.30112651 0.53235838
  0.47417437 0.48421193 0.94408379 0.26310554 0.10269715 0.51596326
  0.19393071 0.79105376 0.83471645 0.47873775 0.68162635 0.86391879
  0.60159383 0.88881024 0.31110542 0.2023949  0.7805151  0.41211696
  0.20705701 0.97713645 0.40978785 0.40333342 0.90568109 0.21274272
  0.72173654 0.63126799 0.59413136 0.14458725 0.19487735 0.18703937
  0.56705692 0.38147941 0.61516561 0.53858713 0.86016403 0.75902687
  0.52246171 0.68830978 0.00709876 0.88425174 0.11846731 0.29312471
  0.4078885  0.36475724 0.16680619 0.71069271 0.96571797 0.46991069
  0.55093127 0.11010015 0.62903409 0.14424162]
 [0.95077452 0.27545562 0.16978393 0.05096134 0.532911   0.83617941
  0.73050127 0.93199503 0.30427534 0.89726459 0.04585212 0.19944362
  0.94764475 0.49140846 0.03253866 0.88716412 0.22193894 0.78655066
  0.12799179 0.59063131 0.8393537

# STEP9: 어텐션 서브레이어의 헤드들의 출력

In [40]:
print("Step9 : We assume we have trained the 8 heads of the attention sub-layer")
z0h1=np.random.random((3, 64))
z0h2=np.random.random((3, 64))
z0h3=np.random.random((3, 64))
z0h4=np.random.random((3, 64))
z0h5=np.random.random((3, 64))
z0h6=np.random.random((3, 64))
z0h7=np.random.random((3, 64))
z0h8=np.random.random((3, 64))

print("shape of one head", z0h1.shape,"demension of 8 heads", 64*8)

Step9 : We assume we have trained the 8 heads of the attention sub-layer
shape of one head (3, 64) demension of 8 heads 512


# STEP10 : 헤드 출력 잇기

In [41]:
print("Step 10: Concantenation of heads 1 to 8 to obtain the original 8x64=512 output dimension of the model")
output_attention=np.hstack((z0h1,z0h2,z0h3,z0h4,z0h5,z0h6,z0h7,z0h8))
print(output_attention)

Step 10: Concantenation of heads 1 to 8 to obtain the original 8x64=512 output dimension of the model
[[0.02905495 0.41798533 0.16726654 ... 0.00117909 0.07807994 0.06751477]
 [0.45622276 0.19515125 0.07170273 ... 0.14464658 0.56401319 0.05848991]
 [0.08724071 0.68086867 0.25875153 ... 0.50944099 0.66014143 0.34502479]]


# Huggine Face에서 Transformer 모델 가져오는 예시

In [42]:
!pip -qq install transformers

In [44]:
from transformers import pipeline
translator = pipeline("translation_en_to_fr")
#One line of code!
print(translator("It is easy to translate languages with transformers", max_length=40))

No model was supplied, defaulted to google-t5/t5-base and revision a9723ea (https://huggingface.co/google-t5/t5-base).
Using a pipeline without specifying a model name and revision in production is not recommended.


RuntimeError: At least one of TensorFlow 2.0 or PyTorch should be installed. To install TensorFlow 2.0, read the instructions at https://www.tensorflow.org/install/ To install PyTorch, read the instructions at https://pytorch.org/.