# Enumerate

In [ ]:
squidgame_info = {'001':'오일남', '067':'강새벽', '199':'알리 압둘', '456':'성기훈'}
# squidgame_info = ['오일남', '강새벽', '알리 압둘', '성기훈']

# squidgame_even = {ind:val for ind, val in enumerate(squidgame_info) if int(ind) % 2 == 0}
# squidgame_even = {ind:val for ind, val in enumerate(squidgame_info)}

for i, v in enumerate(squidgame_info.values()):
    print(i, v)


# print(enumerate(squidgame_info))

# Handling multiple lists

In [ ]:
# Find the longest name
names = ['오일남', '강새벽', '알리 압둘', '성기훈', '조상우']
counts = [len(x) for x in names]
print(counts)

# Initialization
longest_name = None
max_count = 0

# for i in range(len(names)):
#     count = counts[i]
#     if count > max_count:
#         longest_name = names[i]
#         max_count = count
# print(longest_name)

# Using enumerate
# for i, name in enumerate(names):
#     count = counts[i]
#     if count > max_count:
#         longest_name = name
#         max_count = count
# print(longest_name)

# Using zip function
for name, count in zip(names, counts):
    if count > max_count:
        longest_name = name
        max_count = count
print(longest_name)

# Try to use itertools.zip_longest!!

# Modules and packages

### Function:

![func](https://losskatsu.github.io/assets/images/programming/function-module-package/01.JPG)

### Module:

![module](https://losskatsu.github.io/assets/images/programming/function-module-package/03.JPG)

### Package (or Library):

![package](https://losskatsu.github.io/assets/images/programming/function-module-package/07.JPG)

In [ ]:
import math

print(math.sqrt(2))
print(math.sqrt(4))
print(math.pi)

## Import module

In [ ]:
from math import sqrt
print(sqrt(2))
print(pi)

In [ ]:
from math import *

print(sqrt(2))
print(sqrt(4))
print(pi)

In [ ]:
import math as mt

print(mt.sqrt(2))
print(mt.sqrt(4))
print(mt.pi)

## Make your own module

For Google Colab:

In [ ]:
!wget https://raw.githubusercontent.com/crazytb/schadvmachinelearning/f2c57e7ec39d1f03f3c9010d0872872acd5b0eff/mymodule.py

For local IDE:

In [ ]:
# imported the requests library
import requests
url = "https://raw.githubusercontent.com/crazytb/schadvmachinelearning/f2c57e7ec39d1f03f3c9010d0872872acd5b0eff/mymodule.py"
  
# URL of the image to be downloaded is defined as url
r = requests.get(url) # create HTTP response object

# send a HTTP request to the server and save
# the HTTP response in a response object called r
with open("mymodule.py",'wb') as f:
  
    # Saving received content as a png file in
    # binary format
  
    # write the contents of the response (r.content)
    # to a new file in binary mode.
    f.write(r.content)

In [ ]:
# def world():
#     print("Hello, World!")
    
# def add(a, b):
#     return a + b

# def sub(a, b):
#     return a - b


### 1. from \<package\> import \<module\>

In [1]:
from mymodule import world, add, sub

world()
print(add(2, 3))
print(sub(2, 3))

Hello World!
5
5


### 2. from \<package\> import *

In [2]:
from mymodule import *

world()
print(add(2, 3))
print(sub(2, 3))

Hello World!
5
5


### 3. import \<module\> (as \<abbr\>)

In [ ]:
import mymodule

mymodule.world()
print(mymodule.add(2, 3))
print(mymodule.sub(2, 3))

In [3]:
import mymodule as mm

mm.world()
print(mm.add(2, 3))
print(mm.sub(2, 3))

Hello World!
5
5


# Matrix manipulation
## https://numpy.org/doc/stable/reference/arrays.ndarray.html

In [ ]:
import numpy as np

arr = np.matrix([[4, 9, 2], [3, 5, 7], [8, 1, 6]])
print(arr)

## Transpose
## https://numpy.org/doc/stable/reference/generated/numpy.matrix.T.html

In [4]:
import numpy as np

# arr = np.matrix([[4, 9, 2], [3, 5, 7], [8, 1, 6]])
arr = np.matrix('4, 9, 2; 3, 5, 7; 8, 1, 6')
print(arr)

print(arr.T)

print(arr + arr.T)

[[4 9 2]
 [3 5 7]
 [8 1 6]]
[[4 3 8]
 [9 5 1]
 [2 7 6]]
[[ 8 12 10]
 [12 10  8]
 [10  8 12]]


## Flatten
## https://numpy.org/doc/stable/reference/generated/numpy.matrix.T.html

In [ ]:
import numpy as np

arr = np.matrix([[4, 9, 2], [3, 5, 7], [8, 1, 6]])

for i in arr.flatten():
    print(i)

print(arr.flatten()) # 함수
print(arr.A1) # 속성? 애트리뷰트

# How to make module, class, attribute, and function

In [ ]:
def add(a, b):
    return a + b

def sub(a, b):
    return a - b
    
print(add(2, 3))
print(sub(2, 3))

## See mymodule.py

In [ ]:
import mymodule as mm

print(mm.add(2, 3))
print(mm.sub(2, 3))

## Class

In [ ]:
class Cookie:
    pass

# a and b are "instances" of Cookie class.
a = Cookie()
b = Cookie()
print(type(a))

## Attribute

In [ ]:
class Cookie:
    foodtype = "Yummy!" # Class attribute

# a and b are "instances" of Cookie class.
a = Cookie()
b = Cookie()
print(a.foodtype)

## Constructor

In [ ]:
class Cookie:
    
    # Constructor
    def __init__(self, taste = "Yummy!"):
    # def __init__(self, taste):
        self.taste = taste

# a and b are "instances" of Cookie class.
a = Cookie()
b = Cookie("Bad!")
print(a.taste)
print(b.taste)

## Function

In [ ]:
class Cookie:
    
    foodtype = "It's cookie!"

    # Constructor
    def __init__(self, taste = "Yummy!"):
        self.taste = taste
    
    # Function
    def set_taste(self, taste):
        self.taste = taste


# a and b are "instances" of Cookie class.
a = Cookie()
b = Cookie("Bad!")
b.taste = "Hmm... not bad."
print(a.taste)
print(b.taste)